README.md
__tests__/ImageminPlugin.test.js
__tests__/helpers.js
src/ImageminPlugin.js

Remove `name` and `manifest` option, we don't need them, because we don't change name of assets anymore, if you need to change name you can achieve this using the `name` option of `file-loader`, using the `to` option of pattern of `copy-webpack-plugin` (https://github.com/webpack-contrib/copy-webpack-plugin#to), or using other own plugin, changing name is out of scope is plugin and will be mistake in design

Refactor code

---

README.md
src/index.js
src/loader-options.json
src/minify.js
src/plugin-options.json
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/loader-minify-option.test.js
test/loader-severityError-option.test.js
test/minify.test.js
test/plugin-severityError-option.test.js
test/validate-loader-options.test.js
test/validate-plugin-options.test.js

`severityError` option reduced
- Default value `severityError` option is "error"
- Values `true`, `false`, `auto` removed 
No

refactor: severityError option reduced

---

README.md

I believe that `С` is not `C` although it seems to be the same.
And it's causing the CI on webpack documentation to fail, see https://github.com/webpack/webpack.js.org/runs/2733009608?check_suite_focus=true#step:8:8

docs: fix C

---

src/index.js
src/loader-options.json
src/plugin-options.json
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/helpers.js
test/loader-generator-option.test.js
test/validate-loader-options.test.js
test/validate-plugin-options.test.js
types/index.d.ts
types/utils.d.ts

because we affect only on `extension` for generator, developer should use `assetModulePath` or loader name for naming module, we should not have ability to have it, it is out of scope our plugin
Yes
No

refactor!: filename can be used only for minimizer

---

src/index.js
test/ImageminPlugin.test.js
test/fixtures/single-image-loader.js
test/plugin-severityError-option.test.js

fix double minification and memory leak,w e support old loaders, like `file-loader`, and asset modules
No
No

fix: double minification and memory leak

---

package.json
src/cjs.js
src/index.js
src/loader.js
src/utils.js
src/worker.js
test/cjs.test.js
test/worker.test.js
types/cjs.d.ts
types/index.d.ts
types/loader.d.ts
types/worker.d.ts

removed cjs wrapper and generated types in commonjs format (`export =` and `namespaces` used in types), now you can directly use exported types
Potentially yes, but we use `babel` and our code in commonjs format, but types in ESM, so it is fix
No

feat: removed cjs wrapper

---

README.md

We might not need the $ symbol inside the command. If we remove $, It would be easier to copy and run the command. Also, the readme has both commands with $ and without $ so removed $ to make it uniform. 
Fixes typos in config as well.

docs(readme): removed $ and fixes typos

---

README.md

Sharp accepts `jpg` or `jpeg` as output format, but not `mozjpeg`

docs: rename option `mozjpeg` -> `jpeg`

---

README.md

The original config example uses `extendDefaultPlugins`. This creates a warning when running webpack on the config.
Just doc :-) 
I was not 100% sure how to pass the param to `addAttributesToSVGElement`. Is the new structure equivalent to the old one?

Remove usage of deprecated `extendDefaultPlugins` in doc

---

src/utils.js
src/worker.js
test/fixtures/svg-and-jpg.js
test/plugin-minimizer-option.test.js

fix https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/334
No
No

fix: avoid renaming unsupported extensions

---

package.json
tsconfig.json

The built-in linters of VSCode and Visual Studio emmit the error: `Typescript error "Cannot write file ... because it would overwrite input file."` if there is no `outDir` option in tsconfig.json
https://stackoverflow.com/q/55484557
https://stackoverflow.com/q/42609768

chore: move typescript `outDir` option to tsconfig.json

---

.github/workflows/nodejs.yml

Sometimes the time of test actions takes up to 6 hours on windows. https://github.com/webpack-contrib/image-minimizer-webpack-plugin/actions/runs/3008820772/usage
It might be better to limit to 10 minutes.

chore: add timeout to github test action

---

src/utils.js
src/worker.js
test/loader-generator-option.test.js
test/plugin-minimizer-option.test.js
test/worker.test.js
types/utils.d.ts

Makes possible to use minimizer/generator `filename` option with unsupported formats or [multiple minimizers](https://github.com/webpack-contrib/image-minimizer-webpack-plugin#array)
Implementation should return `Promise<null>` for unprocessed data now. But worker still returns not nullable `Promise<WorkerResult>`.

fix: better fix for #334

---

src/utils.js
src/worker.js
test/loader-generator-option.test.js

A useful feature in combination with the resize option. Allow to use `width` and `height` in filename (e.g: filename: "[name]-[width]x[height][ext]")

feat: add `width` and `height` placeholders in filename option

---

src/index.js
src/loader.js
src/utils.js
test/fixtures/generator-and-minimizer-resize-query.js
test/resize-query.test.js
types/index.d.ts
types/loader.d.ts

Adds size query parameters to easier `<picture> srcset` usage. This feature is similar to [parceljs query-parameters](https://parceljs.org/languages/html/#images) for images.
```html
<picture>
<source type="image/avif" srcset="./images/test1.jpg?as=avif&width=400, ./images/test1.jpg?as=avif&width=800 2x">
<source type="image/webp" srcset="./images/test1.jpg?as=webp&width=400, ./images/test1.jpg?as=webp&width=800 2x">
<source type="image/jpeg" srcset="./images/test1.jpg?width=400, ./images/test1.jpg?width=800 2x">
</picture>
```
```js
generator: [
{
preset: 'webp',
implementation: ImageMinimizerPlugin.sharpGenerate,
filename: 'generated-[name]-[width]x[height][ext]',
options: {
encodeOptions: {
webp: {
quality: 90,
},
},
},
},
{
preset: 'avif',
implementation: …
```

feat: add size query parameters

---

src/utils.js
test/loader-generator-option.test.js

Fix `enabled` flag for `squoosh` resize option
```js
implementation: ImageMinimizerPlugin.squooshGenerate,
options: {
resize: {
enabled: false, // <- do not resize
width: 100,
height: 50,
},
```

fix(squoosh): fix resize option enabled flag

---

src/utils.js
test/ImageminPlugin.test.js

`squoosh` throws an unknown format error when using a generator, but not when using a minimizer.
`sharp` also now follows this behavior.

fix: better capability `sharp` and `squoosh` implementations

---

README.md
package-lock.json
package.json
src/index.js
src/utils.js
test/ImageminPlugin.test.js
test/__snapshots__/ImageminPlugin.test.js.snap
test/fixtures/minimizer-only-corrupted.js
test/fixtures/minimizer-only.js
test/fixtures/test-corrupted.svg
tsconfig.json
types/index.d.ts
types/utils.d.ts

The [imagemin](https://github.com/imagemin/imagemin) lib is unmaintained for a year. This means that `svgo` will never be updated to the latest version. So I created an implementation independent of imagemin for svgo.
It's also useful for users using imagemin just to minify only svg files.
I have edited `tsconfig` to avoid svgo bug https://github.com/svg/svgo/issues/1700
Now it has `"skipLibCheck": true`

feat: add `svgo` implementation

---

src/loader.js
src/utils.js
test/ImageminPlugin.test.js
test/utils.test.js
types/utils.d.ts

- flag `isAbsolute` is not relevant then we use it the second time, because the first time we are testing `resourcePath` and converting the filename to a relative path. We need to test it again before using it a second time.
- function `isAbsoluteURL` does not test Windows paths correctly.
- I added a function to change the file extension. It should be safe for windows and posix style path. `path.parse` and `path.join` are platform dependent.

fix: fix some possible issues with file paths

---

README.md

fixes https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/402
fixes https://github.com/webpack-contrib/image-minimizer-webpack-plugin/pull/421
No, our functions still works, just deprecation in docs
No

docs: deprecation of `squoosh`

---

src/utils.js
test/ImageminPlugin.test.js
test/fixtures/svgo-id.svg
test/fixtures/svgo-prefix-id.js

fix: pass the original path to svgo

---

README.md
src/index.js
src/loader.js
src/utils.js
test/fixtures/generator-and-minimizer-percent-resize-query.js
test/resize-query.test.js
types/index.d.ts
types/utils.d.ts

For years I've had to use a custom image loader to allow me to generate non-retina resized images on the fly via webpack from retina-sized images in the source code. But since recently upgrading to webpack 5 and getting familiarized with its new capabilities and patterns (including your plugin here), your plugin's generator functionality seems to be the best place for that sort of functionality instead. So hopefully you agree that this PR adds the ability to do percentage-based resizing of generated images as minimally and idiomatically as I've tried to. But let me know if you have any concerns I might address in order to get this approved and merged. 🙇 🤝 
_no breaking changes_

feat: percent resize unit
