README.md

imageminloader -> imageminLoader (capital L). Fixes #30.

Update README to reflect actual exported loader

---

__tests__/fixtures/svg-with-id.svg
__tests__/minify.test.js
package-lock.json

test: svgo with function in configuration

---

src/ImageminPlugin.js
src/imagemin-loader.js
src/minify.js

refactor: async/await

---

__tests__/loader.test.js
__tests__/minify.test.js
src/ImageminPlugin.js
src/imagemin-loader.js
src/minify.js
src/utils/get-config-for-file.js

always use `relative` paths
Yes
No

refactor: code

---

package-lock.json
package.json
src/utils/normalize-config.js

refactor: migrate on `klona`

---

src/ImageminPlugin.js

fix: compatibility with webpack@5

---

README.md
src/index.js
src/loader-options.json
src/loader.js
src/minify.js
src/plugin-options.json
src/utils/get-config-for-file.js
src/utils/normalize-config.js
src/utils/run-imagemin.js
test/ImageminPlugin.test.js
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/helpers.js
test/loader.test.js
test/minify.test.js
test/validate-loader-options.test.js
test/validate-plugin-options.test.js

Rename the `imageminOptions` to `minimizerOptions`
Yes
No

Rename the imageminOptions to minimizerOptions

---

README.md
src/index.js
src/loader-options.json
src/loader.js
src/minify.js
src/plugin-options.json
test/ImageminPlugin.test.js
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/helpers.js
test/loader.test.js
test/minify.test.js
test/validate-loader-options.test.js
test/validate-plugin-options.test.js

Remove `bail` option in favor `severityError` option
Remove `bail` option in favor `severityError` option
No

Remove bail option in favor severityError option

---

src/minify.js
src/utils/normalize-config.js
test/minify.test.js

Refactor config options
Remove ability use plugin as `function`
No

Refactor config options

---

src/index.js

feat: `avif` extension added to default `test`

---

README.md

docs: readmy updated

---

test/helpers.js
test/loader-filename-option.test.js
test/plugin-filename-option.test.js

Added tests for `filename` option
No
No

Test: filename option

---

src/index.js
test/ImageminPlugin.test.js
test/imagemin-base64.js

Fixed cache name for webpack@5
No
No

Fix: cache name for webpack@5

---

package-lock.json
package.json
src/index.js
src/loader.js

Updated dependencies, including `schema-utils`
No
No

chore: update dependencies

---

src/loader.js
test/loader-deleteOriginalAssets-option.test.js

Refacto: `deleteOriginalAsset` option in loader
No
No

Refactor: deleteOriginalAsset option in loader

---

lint-staged.config.js
package-lock.json
package.json

chore: prepare release

---

package-lock.json
package.json
src/loader-options.json
src/loader.js

refactor: core

---

package-lock.json
package.json
test/ImageminPlugin.test.js
test/helpers.js
test/plugin-severityError-option.test.js

Added test for checking merge asset info
No
No

test: update

---

README.md

This is probably not an actual typo, but it's just a change to use `ImageMinimizerPlugin` in place of `ImageminWebpack` as per the rest of the README
No
N/A

docs(readme): ImageMinimizerPlugin typo/change

---

README.md

Removed `file-loader` and `url-loader` in favor `asset modules`
No
No

docs: removed `file-loader` and `url-loader` in favor `asset modules`

---

README.md
src/index.js
src/loader.js
src/minify.js
src/utils/imageminMinify.js
test/loader-minify-option.test.js
test/minify.test.js
test/plugin-minify-option.test.js

The signature of the `minify` function changed
No
No

refactor: the signature of the minify function changed

---

README.md
package-lock.json
package.json
src/index.js
src/utils/squooshMinify.js
test/loader-minify-option.test.js
test/plugin-minify-option.test.js

feat: `squooshMinify` function added

---

README.md

docs: typo fixed

---

README.md
src/index.js
src/loader-options.json
src/plugin-options.json
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/loader-filename-option.test.js
test/plugin-filename-option.test.js
test/validate-loader-options.test.js
test/validate-plugin-options.test.js
types/index.d.ts

feat: filename option as function

---

.github/workflows/nodejs.yml

**What kind of change does this PR introduce?**
chore
**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
NA
**Summary**
update action
**Does this PR introduce a breaking change?**
no
**Other information**

chore: update github commitlint action

---

src/loader-options.json
src/plugin-options.json
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap

output helpful descriptions and links on errors.
None
No

fix: output helpful descriptions and links on errors

---

.eslintignore
.gitignore
.prettierignore
babel.config.js
globalSetup.js
jest.config.js
package-lock.json
package.json
src/utils.js
test/helpers/built-in-modules/buffer.js
test/helpers/built-in-modules/fs.js
test/helpers/built-in-modules/path.js
test/helpers/built-in-modules/stream.js
test/helpers/built-in-modules/util.js
tsconfig.json
types/index.d.ts
types/utils.d.ts

chore(deps): update imagemin

---

.github/workflows/nodejs.yml
test/ImageminPlugin.test.js
test/helpers.js
test/loader-deleteOriginalAssets-option.test.js
test/loader-filename-option.test.js
test/loader-filter-option.test.js
test/loader-minify-option.test.js
test/loader-severityError-option.test.js
test/loader.test.js
test/plugin-deleteOriginalAssets-option.test.js
test/plugin-filename-option.test.js
test/plugin-filter-option.test.js
test/plugin-loader-option.test.js
test/plugin-minify-option.test.js
test/plugin-severityError-option.test.js
test/validate-loader-options.test.js

ci: add node.js v17

---

README.md
globalSetup.js
jest.config.js
package-lock.json
package.json
src/utils.js
test/api.test.js
types/utils.d.ts

fixes #237
`imageminNormalizeConfig` is now async function
No

Refactor migrate on dynamic import

---

.eslintrc.js
src/index.js
src/loader-options.json
src/loader.js
src/plugin-options.json
src/utils.js
test/ImageminPlugin.test.js
test/__snapshots__/validate-loader-options.test.js.snap
test/fixtures/generator.js
test/loader-deleteOriginalAssets-option.test.js
test/loader-filename-option.test.js
test/loader.test.js
test/plugin-deleteOriginalAssets-option.test.js
test/validate-loader-options.test.js
test/worker.test.js
types/index.d.ts
types/loader.d.ts

Added generator option
Yes, `deleteOriginal` assets was removed from `loader` options
We still need more refactor and test, I will do it in near future

feat: added `generator` option

---

src/index.js
src/loader.js
test/ImageminPlugin.test.js
test/fixtures/generator-and-minimizer.js
test/helpers.js
test/loader.test.js

fix: bugs with generators

---

src/utils.js
test/worker.test.js

respect warnings/errors/info from other worker function
No
No

fix: respect errors

---

src/utils.js
test/__snapshots__/api.test.js.snap
test/worker.test.js

refactor: handle error messages

---

src/index.js
src/loader-options.json
src/loader.js
src/plugin-options.json
src/worker.js
test/ImageminPlugin.test.js
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/helpers.js
test/loader-filter-option.test.js
test/loader-minify-option.test.js
test/loader-minimizer-option.test.js
test/loader-severityError-option.test.js
test/loader.test.js
test/plugin-deleteOriginalAssets-option.test.js
test/plugin-filename-option.test.js
test/plugin-filter-option.test.js
test/plugin-loader-option.test.js
test/plugin-minify-option.test.js
test/plugin-minimizer-option.test.js
test/plugin-severityError-option.test.js
test/validate-loader-options.test.js
test/validate-plugin-options.test.js
test/worker.test.js
types/index.d.ts
types/loader.d.ts
types/utils.d.ts

union `minify` and `minifyOptions` together
Yes
No

Feat union minify and minify options

---

package-lock.json
package.json
src/index.js
src/loader.js
src/utils.js
src/worker.js
test/__snapshots__/api.test.js.snap
test/loader-minimizer-option.test.js
test/plugin-minimizer-option.test.js
tsconfig.json
types/index.d.ts
types/loader.d.ts
types/utils.d.ts
types/worker.d.ts

improve types
Yes, but we are preparing the next release
No

feat: improve types

---

package-lock.json
package.json
src/index.js
src/loader.js
src/utils.js
test/ImageminPlugin.test.js
test/loader.test.js
test/validate-plugin-options.test.js

make `imagemin` optinal, because `imagemin` is outdated and `squoosh` is not stable, the developer will choose own solution
Yes
No

Feat make iamgemin optional

---

package-lock.json
package.json
src/index.js
src/utils.js
test/loader-generator-option.test.js
test/loader-minimizer-option.test.js
types/index.d.ts
types/utils.d.ts

feat: added support for `resize` for `squoosh`

---

src/loader.js
src/utils.js
test/fixtures/loader-other-imports-1.js
test/loader.test.js
test/plugin-minimizer-option.test.js

No need to do it, better describe it in docs, it can be annoying 
Potential
No

feat: do not throw an error on unsupported file types

---

test/fixtures/generator-asset-modules.js
test/helpers.js
test/loader.test.js

Move test + resolve TODO
No
No

test: more

---

src/index.js
src/loader.js
test/ImageminPlugin.test.js

fix unsupported file types skipping + avoid double generator and minimizer
No
No

fix: skip double optimization

---

test/ImageminPlugin.test.js
test/loader-generator-option.test.js
test/loader.test.js
test/plugin-deleteOriginalAssets-option.test.js
test/plugin-minimizer-option.test.js

test: refactor

---

src/loader-options.json
src/loader.js
src/plugin-options.json
test/ImageminPlugin.test.js
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/validate-loader-options.test.js
test/validate-plugin-options.test.js

Allow configuring filename for minimizers
No
No

feat: allow configuring a filename for minimizers

---

README.md
src/index.js

docs: update

---

src/utils.js
test/ImageminPlugin.test.js
test/fixtures/generator-and-minimizer-5.js
test/fixtures/generator.js
test/plugin-deleteOriginalAssets-option.test.js
test/plugin-minimizer-option.test.js
test/worker.test.js
types/index.d.ts

feat: improve error reporting

---

src/index.js
src/utils.js
test/loader.test.js
types/index.d.ts
types/utils.d.ts

fix: reduced memory consumption for `squoosh`

---

src/index.js
test/worker.test.js
types/index.d.ts

fix types internal types, fix types for imagemin, fix types for generator/minimizer, infer options
No
no

Fix typescript

---

README.md
src/index.js
src/loader-options.json
src/plugin-options.json
test/ImageminPlugin.test.js
test/__snapshots__/validate-loader-options.test.js.snap
test/__snapshots__/validate-plugin-options.test.js.snap
test/validate-plugin-options.test.js
types/index.d.ts

fixed #287
No
Allow generating images using the `generator` option, avoid misleading and do behavior more predictable

Feat allow to generate copied assets

---

src/index.js
src/utils.js
test/ImageminPlugin.test.js
test/__snapshots__/ImageminPlugin.test.js.snap
test/fixtures/entry-with-css.js
test/fixtures/style.css

fix memory leaking, free worker in `processAssets` is not safe, because other plugin can add assets and we return it multiple times
No
Also fix compatibility with `sass`, `squoosh` patch global context and adding `navigator`, but it potential unsafe

fix: memory leaking

---

src/loader.js
test/ImageminPlugin.test.js
test/__snapshots__/ImageminPlugin.test.js.snap
test/fixtures/style.css

fix: respect encoding of data uri

---

src/utils.js

improve perf
No
We don't need this hucky workaround if developer use it as plugin

fix: perf for `squoosh`

---

src/index.js
types/index.d.ts

fix: types

---

README.md

docs(readme): added types

---

README.md

fix #306
fix typo in the squoosh-generator-resize section
NA
NA

docs: fix typo in the squoosh-generator-resize section

---

src/utils.js
types/utils.d.ts

fixes https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/336
No
No

fix: sharp types

---

src/utils.js

fix: assets info for sharp

---

src/index.js
src/loader.js
src/utils.js
src/worker.js
types/utils.d.ts
types/worker.d.ts

Some es6+ features were used to improve the readability of the code:
- [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
- [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)
- [Computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names)
- [for-await...of](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for-await...of)
I hope not

refactor: use es6+ features

---

README.md
src/utils.js

Fix regression + update docs
No
@RAX7 I returned `sizeSuffix`, because it will be a breaking change if we will remove it and put TODO for the next major release

chore: fix regression

---

src/index.js
types/index.d.ts

fix: `implementation` types

---

src/utils.js

Pass all resizing parameters to the `sharp` implementation
see: https://sharp.pixelplumbing.com/api-resize#parameters 
e.g:
```js
options: {
resize: {
fit: "contain",
background: [0, 255, 0] // rgb(0, 255, 0)
}
}
```

feat(sharp): more resize options

---

README.md
test/resize-query.test.js

Not only `sharp` supports query parameters

Fix squoosh resize query

---

.github/workflows/nodejs.yml

Add node v18 to test workflow.

chore: add node v18 to test workflow

---

.github/workflows/nodejs.yml

chore:  remove setup git step

---

package-lock.json
package.json
types/index.d.ts

chore: update typescript

---

.github/workflows/dependency-review.yml
.github/workflows/nodejs.yml

chore: update github actions

---

src/loader.js
test/ImageminPlugin.test.js

https://github.com/webpack-contrib/image-minimizer-webpack-plugin/pull/460#discussion_r1890919799
No
No

fix: crash when using filesystem cache
